version: '3.7'

services: 
  trainer-build:
    container_name: linux-trainer
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    image: linux-trainer
    ports: 
      - "127:0.0.1:2222:22"
